module.exports = {
    name: 'quote',
    description: "sends a random quote",
    execute(message, args){
        const quotes = [
        `master have given dobby a taste for human flesh`,
        `do you vore your mother with that mouth`,
        `liam go cry on a paintbrush`,
        `the maraca man has deemed you untrustworthy`,
        `you fucking sopping zucchini`,
        `dishwashe soup`,
        `your hand sauce is loud`,
        `corn can be found`,
        `don't do that, you're gonna catch athlete's mouth`,
        `recessive horse genes`,
        `i don't like this child....it's got the wrong bones`,
        `shredded cheese is a plot by the government to steal our women`,
        `*while upside down* all the pee is going to my head`,
        `honey? you mean BEE syrup??`,
        `my gigabytes are ticklish`,
        `your pickles are leaking`,
        `chicken nuggest?`,
        `i burp, therefore i am`,
        `i snort kiwis whole`,
        `feel the meat on the tangerine`,
        `i am going to solidify in your nasal cavity`,
        `hepatitis E`,
        `tax fraud? i commit gravity fraud`,
        `Richard is my father's name, call me Penis`,
        `the roof is peeing!!`,
        `i'm injecting the chantidote`,
        `for legal reasons my lawyer is not letting me say this....`,
        `Britain’s kryptonite, except instead of throwing green rocks at the man in spandex, \
you have to throw 6 ravens out of the country`,
        `i will unslice your bread`,
        `an atrocity a day keeps god at bay`,
        `:( i got blue in my coffee`,
        `i diagnose you with BEES`,
        `it's time to drain the baby's swamp`,
        `the five elements are earth, water, fire, air, and ear`,
        `prepare for floor donuts`,
        `ask me a purple question`,
        `let's play 'fix that spaghetti'`,
        `whatever türks your gök`,
        `stop putting cheese on my thigh`,
        `why is the tick clocking`,
        `i'm going to sinusoidal you`,
        `Θ cheese`,
        `my toes are squeaky`,
        `eyeball milk \nfresh from the orb`,
        `what're you gonna do? lick my teeth`,
        `if van gogh can lose his ears so can you`,
        `ya, i pee lobsters`,
        `birds need toes and i sneeze whiskey`,
        `bath and body parts`,
        `i'm writing you up for strudels`,
        `it's not robbery, it's surprise communism`,
        `it's not wwiii, it's surprise thermonuclear war`,
        `your pants can't wait for my pee`,
        `TRENT NO!! you can't seduce the troll`,
        `is it raining or is it small intestines`,
        `chicken nuggets are just bird cookies`,
        `who peed in your cereal this morning`,
        `milk is cereal sauce`,
        `my teeth itch`,
        `cheese minecraft`,
        `no?? the carpet is not a tomato`,
        `jacop's glass carpet`,
        `this mexican cheese terrorist looks at money like quentin tarantino looks at feet`,
        `popcorn is short for popular cornelius`,
        `dictator is short for richard potato`,
        `my brother's brother is my grandbrother`,
        `a sond of the droombil dum`,
        `australians eat toilets`,
        `i don't succ, i swaccow`,
        `tater tots is short for potato toddlers`,
        `do whales hear better in milkshakes?`,
        `want my gently used orange`,
        `it's free, like twitter, or theft`,
        `she screwed up on purples`,
        `i have 15 spoons on my person at all times`,
        `i was using my zebra`,
        `arson is tasty`,
        `4379323687532315432324790743211568538589319537739437395319327947585766787654444`,
        `do you ever hear the sound of distressed febreze?`,
        `the element of ketchup is Ke`,
        `this room smells like my mom's bread`,
        `i love to touch pianos`,
        `suck my konnichiweiner`,
        `it's raining anvils and pianos outside`];
        const randomQuote = quotes[Math.floor(Math.random() * quotes.length)];
        message.channel.send(randomQuote);
        //message.channel.send(quotes[quotes.length - 1]);
    }
}
